eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8222

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
        #          filters:
        #            - AuthenticationFilter

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
        #          filters:
        #            - AuthenticationFilter

        # Thêm route để truy cập actuator endpoints của order-service
        - id: order-service-actuator
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/actuator/**
          filters:
            - RewritePath=/api/v1/orders/actuator/(?<segment>.*), /actuator/${segment}

        # Thêm route để truy cập actuator endpoints của product-service
        - id: product-service-actuator
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/actuator/**
          filters:
            - RewritePath=/api/v1/products/actuator/(?<segment>.*), /actuator/${segment}