services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      # Named volume để lưu dữ liệu MySQL
      - mysql_data:/var/lib/mysql
      # Bind mount thư mục cho backup
      - ./mysql-backup:/backup
      # Bind mount cho custom configuration nếu cần
      - ./mysql-conf:/etc/mysql/conf.d
    restart: always

volumes:
  mysql_data: